[package]
name = "unifiedlog_iterator"
version = "0.5.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "0.12.2"
csv = "1.4.0"
chrono = "0.4.43"
log = "0.4.29"
serde_json = "1.0.149"
macos-unifiedlogs = { path = "../../" }
clap = { version = "4.5.56", features = ["derive"] }
libc = "0.2"
