[package]
name = "unifiedlog_iterator"
version = "0.3.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "0.12.2"
csv = "1.3.1"
chrono = "0.4.42"
log = "0.4.28"
serde_json = "1.0.145"
macos-unifiedlogs = { path = "../../" }
clap = { version = "4.5.48", features = ["derive"] }
